//GENERATED by tools/n64-timing/behaviors.py from ares/n64/timing/behaviors.tsv.
//Do not edit. CI runs `behaviors.py --check`, which fails when this file, the
//spec (docs/spec/n64-timing.md) or the check manifest disagree with the TSV.
//
//behaviors.tsv is the single source for three things:
//  1. every timing constant the code uses (this header),
//  2. every row of the timing spec (generated markdown),
//  3. which harness checks prove each row (the `verify` column, resolved
//     against tools/n64-timing/checks.tsv; `pending:<gate>` names a corpus
//     the program cannot run yet and prints as pending, never verified).
//The generator refuses a row with an empty reference or an empty verify list,
//a verify id that the check manifest does not define, and a value-less row
//that code references. That is the map's "no unverified status" rule,
//enforced by the build instead of by review.
//
//Code reads constants only through `Behavior::<id>`. A timing literal in
//ares/n64 outside this header fails tools/n64-timing/lint-literals.py, whose
//error names this file.

namespace ares::Nintendo64::Timing {

enum class Basis : u8 { Measured, Vendor, Datasheet, Wiki, Rtl, Derived, Fit, Assumption };

struct BehaviorInfo {
  const char* id;
  Basis       basis;
  const char* reference;
  const char* verify;  //space-separated check ids
  const char* note;
};

namespace Behavior {
  //value * unit, converted to Clock units by the generator. A row whose value
  //is not an exact number of units is an error unless its basis is Fit; a Fit
  //row rounds to the nearest unit (1/12 rclk, far below the fit's resolution)
  //and the spec prints the rounding next to the row.
  constexpr Clock RiReadHit        = tc(10);
  constexpr Clock RiWriteHit       = tc(4);
  constexpr Clock RiOctbyte        = tc(4);
  constexpr Clock RiRetryClean     = tc(22);
  constexpr Clock RiRetryDirty     = tc(30);
  constexpr Clock RiPostReadGap    = tc(2);
  constexpr Clock RiPostWriteGap   = tc(4);
  constexpr u32   RiMaxBurstBytes  = 128;
  constexpr Clock RiRefreshClean   = rclk(52);
  constexpr Clock RiRefreshDirty   = rclk(54);
  constexpr bool  RiRefreshWaitsForBurst = true;
  constexpr Clock RiOverheadRead   = {54};   //4.5 rclk
  constexpr Clock RiOverheadWrite  = {20};   //1.7 rclk = 20.4 units, Fit rounding
  constexpr Clock RiOverheadRdp    = {20};
  constexpr u8    RiRankRefresh    = 0;
  constexpr u8    RiRankVi         = 1;
  constexpr u8    RiRankOther      = 2;

  constexpr Clock CpuUncachedReadTotal      = pclk(32);
  constexpr Clock CpuUncachedReadDwordTotal = pclk(37);
  constexpr Clock CpuDfillTotal        = pclk(41);
  constexpr Clock CpuIfillStall        = pclk(45);
  constexpr Clock CpuDcacheHit         = pclk(1);
  constexpr Clock CpuLdi               = pclk(1);
  constexpr Clock CpuDcb               = pclk(1);
  constexpr Clock CpuMci               = pclk(1);
  constexpr Clock CpuExcRf             = pclk(5);
  constexpr Clock CpuExcEx             = pclk(6);
  constexpr Clock CpuExcFpuUnimpl      = pclk(7);
  constexpr Clock CpuExcFpuArithExtra  = pclk(5);
  constexpr Clock CpuFpuAdd            = pclk(3);
  constexpr Clock CpuFpuMulS           = pclk(5);
  constexpr Clock CpuFpuMulD           = pclk(8);
  constexpr Clock CpuFpuDivS           = pclk(29);
  constexpr Clock CpuFpuDivD           = pclk(58);
  constexpr Clock CpuFpuTrivial        = pclk(2);
  constexpr Clock CpuFpuForward        = pclk(1);
  constexpr Clock CpuLikelyNullified   = pclk(1);
  constexpr Clock CpuMtc0SlowRegs      = pclk(2);
  constexpr Clock CpuCacheIndexOp      = pclk(5);
  constexpr u8    CpuCountWriteLatency = 1;   //instructions
  constexpr u8    CpuIrqSampleLag      = 1;   //instructions
  constexpr u8    CpuFetchAheadSlots   = 3;
  constexpr u8    CpuWbEntries         = 4;
  constexpr u8    CpuWbBlockEntries    = 2;
  constexpr Clock CpuRcpRegisterRead   = pclk(22);
  constexpr Clock CpuPifRamRead        = rclk(1974);

  constexpr u32   SpDmaBurstBytes      = 128;
  constexpr Clock PiPageSetup          = rclk(15);
  constexpr u32   PiBlockBytes         = 128;
  constexpr Clock PiBlockWriteback     = rclk(28);
  constexpr Clock PiIoBusy             = rclk(134);
  constexpr Clock SiWrite64            = rclk(4065);
  constexpr Clock SiRead64Base         = rclk(13600);
  constexpr u32   AiFetchBytes         = 8;
  constexpr u32   ViLinesPerOutputLine = 3;
  constexpr u32   ViBurstBytes         = 128;

  constexpr u32   RdpCmdFifoDwords     = 30;
  constexpr u32   RdpCmdFetchBurst     = 128;
  constexpr Clock RdpSyncPipe          = rclk(50);
  constexpr Clock RdpSyncTile          = rclk(33);
  constexpr Clock RdpSyncLoad          = rclk(25);
  constexpr Clock RdpSetter            = rclk(1);
  constexpr Clock RdpPrimitiveBase     = rclk(14);
  constexpr u32   RdpSpan1CyclePxPerRclk = 1;
  constexpr u32   RdpSpan2CycleRclkPerPx = 2;
  constexpr u32   RdpFillCopyBytesPerRclk = 8;
  constexpr u32   RdpTmemLoadBytesPerRclk = 8;
  constexpr Clock RdpPipelineDepth     = rclk(25);
  constexpr Clock RdpAtomicDead        = rclk(35);
  constexpr u32   RdpSpanRamHalfBytes  = 64;
  constexpr u32   RdpSpanRamSegmentBytes = 16;
  constexpr u32   RdpColorHalfPixels16bpp = 32;
  constexpr Clock RdpNoisePixelOffset  = rclk(0);
}

//All rows, including rule-valued ones (order, map, rule) that have no
//constant; the harness report lists results per row from this array.
extern const BehaviorInfo behaviors[];
extern const u32 behaviorCount;

}
