//GENERATED by tools/n64-timing/behaviors.py from ares/n64/timing/behaviors.tsv. Do not edit.
//behaviors.py --check fails when this file, docs/spec/n64-timing.md or tools/n64-timing/checks.tsv
//disagree with the table. Times are Clock values (timing/clock.hpp), in 750 MHz units.

namespace Timing {

enum class Basis : u8 { Measured, Vendor, Datasheet, Wiki, Rtl, Derived, Fit, ModelChoice, Legacy };

struct BehaviorInfo {
  const char* id;
  Basis basis;
  const char* value;
  const char* unit;
  const char* reference;
  const char* verify;
  const char* note;
};

namespace Behavior {
  constexpr s64 ClockUnit = 750000000;  //750000000 Hz
  constexpr Ratio ClockVclk = {5500, 357};  //5500/357 units
  constexpr Clock RiReadHit = {30};  //10 tc
  constexpr Clock RiWriteHit = {12};  //4 tc
  constexpr Clock RiOctbyte = {12};  //4 tc
  constexpr Clock RiRetryClean = {66};  //22 tc
  constexpr Clock RiRetryDirty = {90};  //30 tc
  constexpr Clock RiPostReadGap = {6};  //2 tc
  constexpr Clock RiPostWriteGap = {12};  //4 tc
  constexpr s64 RiMaxBurst = 128;  //128 B
  constexpr Clock RiRefreshClean = {624};  //52 rclk
  constexpr Clock RiRefreshDirty = {648};  //54 rclk
  constexpr bool RiRefreshWaitsForBurst = true;  //1 flag
  constexpr s64 RiRankRefresh = 0;  //0 rank
  constexpr s64 RiRankVi = 1;  //1 rank
  constexpr s64 RiRankOther = 2;  //2 rank
  constexpr Clock RiOverheadRead = {54};  //4.5 rclk
  constexpr Clock RiOverheadVi = {0};  //0 rclk
  constexpr Clock RiOverheadWrite = {12};  //1 rclk
  constexpr Clock RiOverheadRdp = {20};  //20 units
  constexpr Clock RiRequestLatency = {1};  //1 units
  constexpr Clock CpuUncachedReadTotal = {256};  //32 pclk
  constexpr Clock CpuUncachedReadDwordTotal = {296};  //37 pclk
  constexpr Clock CpuDfillTotal = {328};  //41 pclk
  constexpr Clock CpuIfillStall = {360};  //45 pclk
  constexpr Clock CpuDcacheHit = {8};  //1 pclk
  constexpr Clock CpuLdi = {8};  //1 pclk
  constexpr Clock CpuDcb = {8};  //1 pclk
  constexpr Clock CpuMci = {8};  //1 pclk
  constexpr Clock CpuExcRf = {40};  //5 pclk
  constexpr Clock CpuExcEx = {48};  //6 pclk
  constexpr Clock CpuExcFpu = {40};  //5 pclk
  constexpr Clock CpuFpuAdd = {24};  //3 pclk
  constexpr Clock CpuFpuMulS = {40};  //5 pclk
  constexpr Clock CpuFpuMulD = {64};  //8 pclk
  constexpr Clock CpuFpuDivS = {232};  //29 pclk
  constexpr Clock CpuFpuDivD = {464};  //58 pclk
  constexpr Clock CpuFpuTrivial = {16};  //2 pclk
  constexpr Clock CpuFpuForward = {8};  //1 pclk
  constexpr Clock CpuIssue = {8};  //1 pclk
  constexpr Clock CpuMult = {40};  //5 pclk
  constexpr Clock CpuDmult = {64};  //8 pclk
  constexpr Clock CpuDiv = {296};  //37 pclk
  constexpr Clock CpuDdiv = {552};  //69 pclk
  constexpr Clock CpuFpuSqrtS = {232};  //29 pclk
  constexpr Clock CpuFpuSqrtD = {464};  //58 pclk
  constexpr Clock CpuFpuConvert = {40};  //5 pclk
  constexpr Clock CpuFpuCvtSD = {16};  //2 pclk
  constexpr Clock CpuLikelyNullified = {8};  //1 pclk
  constexpr Clock CpuEret = {24};  //3 pclk
  constexpr Clock CpuMtc0SlowRegs = {16};  //2 pclk
  constexpr Clock CpuCacheIndexLoadTag = {48};  //6 pclk
  constexpr Clock CpuCountWriteHold = {16};  //2 pclk
  constexpr s64 CpuFetchAheadSlots = 3;  //3 instr
  constexpr s64 CpuWbEntries = 4;  //4 entries
  constexpr s64 CpuWbBlockEntries = 2;  //2 entries
  constexpr Clock CpuRcpRegisterRead = {176};  //22 pclk
  constexpr Clock CpuPifRamRead = {23688};  //1974 rclk
  constexpr Clock SysadRdramWritePeriod = {144};  //12 rclk
  constexpr Clock SysadRdramBlockWritePeriod = {144};  //12 rclk
  constexpr Clock SysadRegisterWrite = {60};  //5 rclk
  constexpr s64 CpuWiredWriteLatency = 2;  //2 instr
  constexpr s64 SpDmaBurst = 128;  //128 B
  constexpr Ratio SpDmaRateCheck = {13, 2};  //6.5 B/rclk
  constexpr Clock RspSlot = {12};  //1 rclk
  constexpr Clock PiPageSetup = {180};  //15 rclk
  constexpr Clock PiHalfwordBias = {24};  //2 rclk
  constexpr s64 PiBlockBytes = 128;  //128 B
  constexpr Clock PiBlockWriteback = {336};  //28 rclk
  constexpr Clock PiIoBusy = {1608};  //134 rclk
  constexpr Clock SiWrite64 = {48780};  //4065 rclk
  constexpr Clock SiRead64Base = {163200};  //13600 rclk
  constexpr s64 AiFetchBytes = 8;  //8 B
  constexpr s64 ViLinesPerOutputLine = 3;  //3 lines
  constexpr s64 ViBurst = 128;  //128 B
  constexpr s64 ViVclkPerPixel = 4;  //4 vclk/px
  constexpr s64 RdpCmdFifoDwords = 30;  //30 dwords
  constexpr s64 RdpCmdFetchBurst = 128;  //128 B
  constexpr s64 RdpXbusFetchRate = 8;  //8 B/rclk
  constexpr Clock RdpSyncPipe = {600};  //50 rclk
  constexpr Clock RdpSyncTile = {396};  //33 rclk
  constexpr Clock RdpSyncLoad = {300};  //25 rclk
  constexpr Clock RdpSyncFull = {600};  //50 rclk
  constexpr Clock RdpSetter = {12};  //1 rclk
  constexpr Clock RdpPrimitiveBase = {144};  //12 rclk
  constexpr s64 RdpSpanDeadPixels = 2;  //2 px
  constexpr Clock RdpSpanLineGap = {24};  //2 rclk
  constexpr s64 RdpSpan1cycle = 1;  //1 px/rclk
  constexpr Ratio RdpSpan2cycle = {1, 2};  //0.5 px/rclk
  constexpr s64 RdpFillCopyRate = 8;  //8 B/rclk
  constexpr s64 RdpTmemLoadRate = 8;  //8 B/rclk
  constexpr Clock RdpPipelineDepth = {300};  //25 rclk
  constexpr Clock RdpAtomicDead = {420};  //35 rclk
  constexpr s64 RdpSpanRamHalf = 64;  //64 B
  constexpr s64 RdpSpanRamSegment = 16;  //16 B
  constexpr s64 RdpColorHalfPixels16bpp = 32;  //32 px
  constexpr Clock RdpNoisePixelOffset = {0};  //0 rclk
}

inline constexpr BehaviorInfo behaviors[] = {
  {"clock.unit", Basis::Derived, "750000000", "Hz", "clocks.md: LCM of RCLK 250, PClock 93.75, RCP 62.5 MHz (X2 x17)", "nemu64:rsp_timing/clock-cpu-vs-rdp", ""},
  {"clock.vclk", Basis::Derived, "5500/357", "units", "clocks.md: VCLK = 315/22 MHz x 17/5 (X1); exact rational", "mm:south-clock-town", "AI and VI share the accumulator; removes the +33 ppm AI truncation"},
  {"scheduler.tie-rank", Basis::ModelChoice, "Bus,Events,SysAD,RDP,RSP,CPU", "order", "none: equal-time ordering between independent RCP blocks is unpublished", "det stepcap unit:timeline", "convention; cannot be observed by a test ROM except through an exact tie"},
  {"ri.read-hit", Basis::Datasheet, "10", "tc", "NEC uPD488170L tReadHit (rdram-bus-arbitration.md B8)", "unit:ri-cost-table nemu64:timing/load-from-uncached-vi-off", ""},
  {"ri.write-hit", Basis::Datasheet, "4", "tc", "NEC uPD488170L tWriteHit (B8)", "unit:ri-cost-table bench:mi-memset-uncached", ""},
  {"ri.octbyte", Basis::Datasheet, "4", "tc", "NEC uPD488170L 2 B per tc (B8)", "unit:ri-cost-table bench:sp-dma-sweep", ""},
  {"ri.retry-clean", Basis::Datasheet, "22", "tc", "NEC tRetrySensedClean = 7+7+8 at IPL3 RasInterval 1/7/10/4 (B8, s.2)", "unit:ri-cost-table nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"ri.retry-dirty", Basis::Datasheet, "30", "tc", "NEC tRetrySensedDirty (B8)", "unit:ri-cost-table bench:dirty-row-sweep", ""},
  {"ri.post-read-gap", Basis::Datasheet, "2", "tc", "NEC tPostMemReadDelay (B8)", "bench:sp-dma-sweep", ""},
  {"ri.post-write-gap", Basis::Datasheet, "4", "tc", "NEC tPostMemWriteDelay (B8)", "bench:sp-dma-sweep", ""},
  {"ri.max-burst", Basis::Wiki, "128", "B", "n64brew RDRAM_Interface Count, 1-16 octbytes (B2)", "unit:ri-split", ""},
  {"ri.bank-of", Basis::Wiki, "addr[22:20]", "map", "n64brew RDRAM_Interface address mapping (B6)", "nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"ri.row-of", Basis::Datasheet, "addr[19:11]", "map", "NEC 2 KiB RowSenseAmpCache (B6)", "nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"ri.refresh-clean", Basis::Vendor, "52", "rclk", "IPL3 6105 RI_REFRESH 0x007E3634 CleanRefreshDelay (B12)", "bench:uncached-vs-hpos", ""},
  {"ri.refresh-dirty", Basis::Vendor, "54", "rclk", "IPL3 6105 RI_REFRESH DirtyRefreshDelay (B12)", "bench:uncached-vs-hpos", ""},
  {"ri.refresh-trigger", Basis::Wiki, "hsync", "event", "n64brew RDRAM_Interface: one SetRR per VI HSYNC (B11)", "bench:uncached-vs-hpos", "SOURCE CONFLICT: rdram-bus-arbitration.md B11 says refresh runs before VI init (H_TOTAL 0x7FF, ~42 us per line); nemu64-test's VI-off loads (nemu64:timing/load-from-uncached-vi-off, nemu64:timing/load-miss-vi-off) average 32.54 pclk uncached, which a 52-rclk holdoff every line would raise by about 2. The model follows the nemu64 data: refresh runs only while the VI is active (vi.cpp VI::line). Reason: it is the only measurement of VI-off timing, and B11's pre-init claim is from n64brew prose, unmeasured. A blank VI sending no HSYNC is consistent with both; a pre-init refresh at the 0x7FF line rate remains unverified"},
  {"ri.refresh-waits-for-burst", Basis::ModelChoice, "1", "flag", "no mid-burst preemption (B5); refresh waits for the in-flight burst", "bench:uncached-vs-hpos", "calibration #16"},
  {"ri.arbitration", Basis::ModelChoice, "rank,arrival,requester,sequence", "order", "none published (B4); VI first is an inference from its hard real-time role", "nemu64:timing/load-miss-vi-on thar0:vi-on-separate-bank", "calibration #16 re-ranks via ri.rank.*; rejected alternatives recorded: fixed list VI,AI,SI,PI,CPU,SP,DP (fable), Refresh>VI>AI>CPU>SI>PI>SP>DPcmd>DPmem (sonnet), MiSTer DDR3Mux order"},
  {"ri.rank.refresh", Basis::Wiki, "0", "rank", "n64brew: refresh holds off every client (B12)", "bench:uncached-vs-hpos", ""},
  {"ri.rank.vi", Basis::ModelChoice, "1", "rank", "inference: VI is the only hard real-time client (B4)", "nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"ri.rank.other", Basis::ModelChoice, "2", "rank", "none published (B4): all other clients first-come first-served", "nemu64:timing/load-miss-vi-on", ""},
  {"ri.overhead-read", Basis::Fit, "4.5", "rclk", "hcs64 SP DMA 3.7 B/pclk = 23 rclk per 128 B minus wire 18.5 (dma-timing.md, B10)", "bench:sp-dma-sweep", "verify-is-fit: bench:sp-dma-sweep reports hcs64's 5.55 B/rclk, the fit's own data, and asserts only the write point; no check decides a read DMA. Direction of hcs64 run unstated"},
  {"ri.overhead-vi", Basis::Derived, "0", "rclk", "vi-fetch.md MM bus-occupancy estimate: a 128 B VI read holds the channel for the NEC wire time (74 tc hit, 96 clean miss, 104 dirty miss) plus the 2 tc post-read gap; no reference charges scanout the RI overhead that ri.overhead-read fits from SP DMA throughput (B10)", "nemu64:timing/load-from-uncached-vi-on-other-bank nemu64:timing/load-miss-vi-on", "ri counters on MM: VI channel share against the 6.5-9.0% band of vi-fetch.md"},
  {"ri.overhead-write", Basis::Fit, "1", "rclk", "n64brew MI memset RSP DMA 2.58 ms/MiB = 19.7 rclk per 128 B; the RI decides on rclk edges, so a 128 B write repeats every 17 wire + 1 gap + ceil(overhead) rclk: 1 gives 19, the 1.7 of the unquantized fit gives 20 (B10)", "bench:mi-memset-rspdma", "verify-is-fit: both checks assert n64brew's 2.58 ms/MiB memset (6.5 B/rclk), the data the fit solves, and no other check decides a write DMA"},
  {"ri.overhead-rdp", Basis::ModelChoice, "20", "units", "assumed equal to the unquantized ri.overhead-write fit (1.7 rclk, 20 units after rounding); span-ram.md row 10 says the RDP path is unmeasured", "thar0:imrd-1cycle", "calibration #16"},
  {"ri.request-latency", Basis::ModelChoice, "1", "units", "none published: ADR 0001 Decision 1 needs a request to reach the arbiter after its post, so a decision never races an equal-time post; one unit is the least that does", "det stepcap", ""},
  {"cpu.uncached-read-total", Basis::Measured, "32", "pclk", "nemu64-test cache.rs:288-382 median, VI off", "nemu64:timing/load-from-uncached-vi-off", "sysad.fixed-path is derived from this minus modeled wire"},
  {"cpu.uncached-read-dword-total", Basis::Measured, "37", "pclk", "n64-systembench main.c:572-584 U64 (cited value; ROM is romgen's)", "bench:uncached-sizes", ""},
  {"cpu.dfill-total", Basis::Measured, "41", "pclk", "nemu64-test cache.rs:193-286 median, VI off", "nemu64:timing/load-miss-vi-off", "assumes the nemu64 D-fill measurement is a clean row miss (open row not dirty); a dirty-row miss would add the writeback and the 41 would not be the clean-miss cost"},
  {"cpu.ifill-stall", Basis::Derived, "45", "pclk", "NEC Table 11-2 with M from D-fill (cpu-memory-costs.md)", "bench:ifill-isolated", "no public hardware value; the bench reports"},
  {"cpu.dcache-hit", Basis::Measured, "1", "pclk", "nemu64-test Cached loads and store, 19 cases", "nemu64:timing/cached-loads-and-store", ""},
  {"cpu.ldi", Basis::Vendor, "1", "pclk", "NEC VR4300 UM s.4.6.5; n64brew register-field overlap rule", "nemu64:timing/cpu-register-dependency", ""},
  {"cpu.dcb", Basis::Vendor, "1", "pclk", "NEC VR4300 UM s.4.6.7", "nemu64:timing/cpu-register-dependency", ""},
  {"cpu.mci", Basis::Measured, "1", "pclk", "nemu64-test MFC0 then dependent (C9)", "nemu64:timing/cpu-register-dependency", ""},
  {"cpu.exc-rf", Basis::Measured, "5", "pclk", "nemu64-test Exceptions JustFire, faulting issue slot through the handler's first: BREAK, SYSCALL, RI (_I28), CpU (COP1 and COP2 ops with CU clear)", "nemu64:timing/exceptions", ""},
  {"cpu.exc-ex", Basis::Measured, "6", "pclk", "nemu64-test Exceptions JustFire: Ov (ADD, ADDI, DADD, DADDI, SUB, DSUB), all traps, AdEL and TLBL on every load kind", "nemu64:timing/exceptions", "AdES, TLBS and Mod have no test; inferred to share the load's stage"},
  {"cpu.exc-fpu", Basis::Measured, "5", "pclk", "nemu64-test COP1Instructions32/64 JustFire = FPU detection latency + 5: ADD.S overflow 3+5, MUL.S inexact 5+5, DIV.S inexact 29+5, ADD.W unimplemented 2+5 (C1)", "nemu64:timing/cop1instructions32 nemu64:timing/cop1instructions64", "the detection latency is cpu.exc-fpu-detect; a CTC1-raised FPE has no reference and costs nothing beyond its slot"},
  {"cpu.exc-fpu-detect", Basis::Measured, "operands-or-result", "rule", "nemu64-test COP1Instructions32/64 JustFire: an FPE raised from the result takes the op's latency (fast operands included; CEIL.W.S 2^31 and ROUND.W.D 0x41efffffffffffff take 5+5); one raised from the operands takes min(latency, cpu.fpu-trivial): denormal or NaN operand, conversion to W of |x| >= 2^32 or Inf (ROUND.W.D 2^32 takes 2+5), to L of |x| >= 2^53, from L of |x| >= 2^55, a W or L format op with an S form at the S form's latency (ADD.W 2+5, _F16.W 1+5)", "nemu64:timing/cop1instructions32 nemu64:timing/cop1instructions64", "the rule is read off the same tables that check it, as cpu.fpu-trivial is"},
  {"cpu.fpu-add", Basis::Measured, "3", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-mul-s", Basis::Measured, "5", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-mul-d", Basis::Measured, "8", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions64", ""},
  {"cpu.fpu-div-s", Basis::Measured, "29", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-div-d", Basis::Measured, "58", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions64", ""},
  {"cpu.fpu-trivial", Basis::Measured, "2", "pclk", "nemu64-test COP1 value tables (operand 0, -0, Inf, qNaN)", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-forward", Basis::Measured, "1", "pclk", "nemu64-test COP1RegisterDependency", "nemu64:timing/cop1-register-dependency", ""},
  {"cpu.issue", Basis::Measured, "1", "pclk", "nemu64-test PreciseMeasureJustNOPs: N NOPs cost N", "nemu64:timing/just-nops", ""},
  {"cpu.mult", Basis::Measured, "5", "pclk", "nemu64-test SingleInstructionCPUTiming MULT/MULTU; HiLoInterlockTiming: the pipeline stalls for the full duration", "nemu64:timing/mult-div-interlock", ""},
  {"cpu.dmult", Basis::Measured, "8", "pclk", "nemu64-test SingleInstructionCPUTiming DMULT/DMULTU; HiLoInterlockTiming", "nemu64:timing/mult-div-interlock", ""},
  {"cpu.div", Basis::Measured, "37", "pclk", "nemu64-test SingleInstructionCPUTiming DIV/DIVU; HiLoInterlockTiming", "nemu64:timing/mult-div-interlock", ""},
  {"cpu.ddiv", Basis::Measured, "69", "pclk", "nemu64-test SingleInstructionCPUTiming DDIV/DDIVU; HiLoInterlockTiming", "nemu64:timing/mult-div-interlock", ""},
  {"cpu.fpu-sqrt-s", Basis::Measured, "29", "pclk", "nemu64-test COP1 tables (SQRT.S 123, 16, 4, 1)", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-sqrt-d", Basis::Measured, "58", "pclk", "nemu64-test COP1 tables (SQRT.D 123, 16, 4, 1)", "nemu64:timing/cop1instructions64", ""},
  {"cpu.fpu-convert", Basis::Measured, "5", "pclk", "nemu64-test COP1 tables (CVT.W/L, CVT.S/D from W/L); ROUND, TRUNC, CEIL, FLOOR assumed equal to CVT.W/L", "nemu64:timing/cop1instructions32 nemu64:timing/cop1instructions64", ""},
  {"cpu.fpu-cvt-s-d", Basis::Measured, "2", "pclk", "nemu64-test COP1 tables (CVT.S.D)", "nemu64:timing/cop1instructions64", ""},
  {"cpu.likely-nullified", Basis::Measured, "1", "pclk", "nemu64-test Likely branch (C8)", "nemu64:timing/likely-branch", ""},
  {"cpu.eret", Basis::Fit, "3", "pclk", "nemu64-test Exceptions Roundtrip (BREAK, SYSCALL + handler + ERET) 15, less the modeled BREAK fault (cpu.exc-rf) and handler: the ERET costs 3 including its issue slot", "nemu64:timing/exception-roundtrip", "verify-is-fit: the two Roundtrip values are the only measurement of ERET"},
  {"cpu.mtc0-slow-regs", Basis::Measured, "2", "pclk", "nemu64-test Random, EntryLo0/1, EntryHi, reg7 (C5)", "nemu64:timing/individual-instructions", ""},
  {"cpu.cache-index-load-tag", Basis::Measured, "6", "pclk", "nemu64-test CPURegisterDependency 'LD; CACHE (DataIndexLoadTag)' 7, 8, 8: the CACHE costs 6 including its issue slot (C10)", "nemu64:timing/cache", "the other CACHE ops have no measurement and cost their issue slot"},
  {"cpu.count-write-hold", Basis::Fit, "2", "pclk", "nemu64-test cop0hazard CountHazards: the four MFC0 COUNT right after an MTC0 COUNT of v read v, v, v, v+1, for six values of v. One MFC0 issues per pclk and COUNT ticks every 2 pclk, so three equal reads need the counter to stop; holding the written value 2 pclk from the MTC0's execute is the only whole-pclk hold that gives all four (nemu64-timing-failures.md: counting resumes only after the write retires)", "nemu64:cop0hazard/count", "verify-is-fit: the COUNT hazards test is the only measurement of the hold's length. The timing harness resets COUNT with an MTC0 and only sees the hold's parity: a 1 pclk hold fails 988 of its 1604 values, 0 and 2 pass"},
  {"cpu.irq-sample", Basis::Fit, "pending-at-two-boundaries", "rule", "nemu64-test cop0hazard: SoftwareInterrupt1 (enabled, hazard) takes Int one instruction after the instruction following the MTC0 Cause that sets IP1; SoftwareInterrupt12 takes it there although that second instruction clears IP1; SoftwareInterrupt1 (enable but disable right away), where the clearing MTC0 Cause directly follows the setting one, never takes it. Taking Int before an instruction only if the interrupt condition held at the previous instruction boundary too fits all three; delaying the CP0 write by one instruction instead takes the third", "nemu64:cop0hazard/softwareinterrupt", "verify-is-fit: the three SoftwareInterrupt values are the only measurement. Applied to the RCP and timer lines too, inferred (one sampler for every Cause.IP bit), no test"},
  {"cpu.fetch-ahead-slots", Basis::Derived, "3", "instr", "nemu64-test cycle set SMC: a store fewer than 3 slots ahead is not seen", "nemu64:cycle/smc", "fable chose 2; the window is sized so both readings fit, the cycle set decides"},
  {"cpu.dirty-miss-order", Basis::Vendor, "fill-then-writeback", "order", "NEC s.12.5.2-12.5.3 p.304; R4300i datasheet p.8-9 (vr4300-wb.md)", "bench:dirty-miss-isolated", ""},
  {"cpu.wb-entries", Basis::Vendor, "4", "entries", "NEC s.4.9 p.120; R4300i datasheet p.9", "nemu64:timing/uncached-write-buffer", ""},
  {"cpu.wb-block-entries", Basis::Vendor, "2", "entries", "R4300i datasheet p.9", "bench:mi-memset-cached", ""},
  {"cpu.wb-release", Basis::Vendor, "slot", "rule", "NEC 'has a space' (s.4.9) chosen over R4300i datasheet 'emptied'; burst shape only", "bench:wb-fifth-store", "conflict recorded; no public hardware value"},
  {"cpu.rcp-register-read", Basis::Measured, "22", "pclk", "n64-systembench VI_CONTROL read 24 minus about 2 harness (cited value)", "bench:rcp-reg-read", ""},
  {"cpu.pif-ram-read", Basis::Measured, "1974", "rclk", "n64-systembench PIF RAM read (cited value)", "bench:pif-ram-read", ""},
  {"sysad.rdram-write-period", Basis::Fit, "12", "rclk", "n64brew MIPS_Interface memset, 64-bit uncached writes 25.7 ms/MiB = 18.38 pclk = 12.25 rclk per SD (vr4300-wb.md), less refresh (1.3%, rdram-bus-arbitration.md B12), on the SClock grid: 12 rclk gives 18.28 pclk, the rest is inferred, not measured, to be VI fetch contention (plan T11)", "bench:mi-memset-uncached", "verify-is-fit: the uncached memset is the only measurement of an uncached RDRAM write drain and the fit's data. Drain period of one uncached RDRAM write, request to EOK at row hit. T11: the modeled VI fetch adds 1.65 pclk per SD over the bench's VI-off point (19.70 vs 18.05), not the 0.1 the reference infers (vi.burst note)"},
  {"sysad.rdram-block-write-period", Basis::Fit, "12", "rclk", "n64brew MIPS_Interface memset, 64-bit cached writes 49.8 ms/MiB = 71.24 pclk per line (vr4300-wb.md), less the modeled fill (a dirty row miss behind the victim), the victim write (a clean row miss), the store issues and refresh, on the SClock grid: 12 rclk gives 71.0 pclk, the rest is inferred, not measured, to be VI fetch contention (plan T11)", "bench:mi-memset-cached bench:dirty-miss-isolated", "verify-is-fit: the cached memset is the fit's data and bench:dirty-miss-isolated only reports (no hardware value). Drain period of one D-cache line writeback, request to EOK at row hit; equal to the single-write period. T11: the modeled VI fetch adds 5.28 pclk per line over the bench's VI-off point (75.77 vs 70.49), not the 0.2 the reference infers (vi.burst note)"},
  {"sysad.register-write", Basis::ModelChoice, "5", "rclk", "no hardware measurement (vr4300-wb.md, RCP register row); MiSTer memorymux.vhd:346-425 holds a register write 3 RCP clocks after the 2-SClock address and data phases", "pending:no-corpus", "a posted write to an RCP register, the PI or the PIF takes effect this long after it starts draining"},
  {"cpu.random-rule", Basis::Fit, "decrement-per-instruction", "rule", "nemu64-test Random (decrement): Random after 1, 16, 31 and 100 instructions for Wired 0-63, from 31 down to Wired and wrapping (through 63 when Wired > 31); Random (masking): an MTC0 Random is ignored, and counting PClock cycles instead of instructions reads 11 where 27 is expected, so stall cycles do not count", "nemu64:timing/random nemu64:cop0hazard/random-read-early", "Random (read early) checks the decrement over 10 instructions from other code (21)"},
  {"cpu.wired-write-latency", Basis::Fit, "2", "instr", "nemu64-test Random (decrement): Random reads 30 three instructions after an MTC0 Wired, for every Wired, so the reload to 31 lands two instructions after the write", "nemu64:timing/random nemu64:cop0hazard/random-read-early", "Random (read early) checks the landing independently: one instruction after the write Random still follows the previous Wired bound (29), two after it reads 31"},
  {"cpu.ctc1-fpe-ce", Basis::Fit, "following-instruction-bits-27-26", "rule", "nemu64-test cop1 FireExceptionViaCTC1 followed by MFC1 and by MFC2: EPC is the CTC1 and Cause.CE is 1 and 2, the coprocessor of the instruction after it (nemu64-timing-failures.md, cycle set: an inference from the expected values)", "nemu64:cycle/ctc1", "verify-is-fit: the two CTC1 values are the only measurement. After an instruction outside COP1-3 the field comes from the same opcode bits, inferred, no test"},
  {"sp.dma-burst", Basis::ModelChoice, "128", "B", "inference: RI maximum matches the measured ~20 rclk per 128 B (dma-timing.md)", "bench:sp-dma-sweep", ""},
  {"sp.dma-rate-check", Basis::Measured, "6.5", "B/rclk", "n64brew MI page RSP DMA memset 2.58 ms/MiB; hcs64 5.55 conflicts (direction unstated)", "bench:sp-dma-sweep", "the bench reports both directions"},
  {"rsp.slot", Basis::Wiki, "1", "rclk", "clocks.md: the RSP runs on the RCP clock (n64brew Clock_Timing; SDK pro-man ch.3 RCP 62.5 MHz); one pipeline slot, an issue or a bubble, per clock", "nemu64:rsp_timing/sll", "RSP::Pipeline charges it per issued pair and per stall bubble (ADR 0001 keeps the RSP pipeline as the RSP cost model)"},
  {"pi.page-setup", Basis::Wiki, "15", "rclk", "n64brew PI: 14 + LAT + 1 with LAT separate (dma-timing.md)", "pidma:logs bench:pi-dma-sizes", ""},
  {"pi.halfword-bias", Basis::Wiki, "2", "rclk", "n64brew PI domain registers: PWD and RLS hold cycles minus 1, so a halfword takes PWD + 1 + RLS + 1 RCP clocks (dma-timing.md)", "pidma:logs bench:pi-dma-sizes", ""},
  {"pi.block-bytes", Basis::Wiki, "128", "B", "n64brew PI; rasky n64_pi_dma_test", "pidma:logs", ""},
  {"pi.block-writeback", Basis::Derived, "28", "rclk", "dma-timing.md fit to systembench PI DMA rows; the bus model supplies the wire part", "pidma:logs bench:pi-dma-sizes", ""},
  {"pi.io-busy", Basis::Measured, "134", "rclk", "n64-systembench PI I/O W (cited value)", "bench:pi-io-write", ""},
  {"si.write64", Basis::Measured, "4065", "rclk", "n64-systembench SI DMA 64 B to PIF (cited value)", "bench:si-dma", ""},
  {"si.read64-base", Basis::Derived, "13600", "rclk", "ares pif.estimateTiming (systembench-derived)", "bench:si-dma", ""},
  {"ai.fetch-bytes", Basis::Vendor, "8", "B", "US 6,166,748 '8 bytes at a time' (dma-timing.md)", "mm:south-clock-town", "functional; contention effect 0.026% of peak"},
  {"vi.lines-per-output-line", Basis::Vendor, "3", "lines", "SDK pro-man s.24.4; US 6,166,748 FIG. 34 (vi-fetch.md)", "nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"vi.burst", Basis::ModelChoice, "128", "B", "inference from the 64-px X_SCALE erratum and the RI maximum (vi-fetch.md)", "bench:uncached-vs-hpos", "T11 run: MM scanout holds the channel 354.5 rclk per HSYNC line (8.9% of a 3972-rclk NTSC line; vi-fetch.md 7.2-10.0%), yet costs other clients more than five hardware measurements allow: nemu64 uncached other-bank mean 37.9 vs 32.5 (VI off 32.54); memset uncached 19.70 vs 18.38 pclk/SD, cached 75.77 vs 71.24 pclk/line, RSP DMA 6.08 vs 6.5 B/rclk; SP DMA 4 KiB write 5.85 vs 6.5 B/rclk. Unmeasured inputs: this burst size, ri.overhead-read (an SP DMA fit) applied to VI, ri.rank.vi; calibration #16"},
  {"vi.fetch-window", Basis::Wiki, "active-line", "rule", "n64brew VI_H_VIDEO; US 6,166,748 'in synchronism with the line scanning'", "bench:uncached-vs-hpos", ""},
  {"vi.vclk-per-pixel", Basis::Wiki, "4", "vclk/px", "VI_H_SYNC counts the line in quarter pixels and VI_H_VIDEO in pixels: NTSC H_SYNC 3093 is a 773.5-px line, H_VIDEO 108-748 its 640 active px (vi-fetch.md, MM bus-occupancy inputs; n64brew Video_Interface)", "bench:uncached-vs-hpos", ""},
  {"rdp.cmd-fifo-dwords", Basis::Wiki, "30", "dwords", "n64-systemtest rdp/mod.rs:21-23 author note: CURRENT reaches START+240 while frozen", "rdpstat:current-prefetch", "no test asserts it; MiSTer uses 64; calibration #16"},
  {"rdp.cmd-fetch-burst", Basis::ModelChoice, "128", "B", "RI maximum; MiSTer fetches <= 22 words", "rdpstat:current-prefetch", "calibration #16"},
  {"rdp.xbus-fetch-rate", Basis::ModelChoice, "8", "B/rclk", "cen64 jgemu interface.c fetches commands 64 bits per clock (rdp-command-timing.md, Command fetch row); the X bus is private to the RSP and RDP, so no RI traffic", "rdpstat:xbus", "no hardware measurement"},
  {"rdp.sync-pipe", Basis::Wiki, "50", "rclk", "n64brew Commands (Tharo rev 5366)", "bench:rdp-sync-sweep", ""},
  {"rdp.sync-tile", Basis::Wiki, "33", "rclk", "n64brew Commands", "bench:rdp-sync-sweep", ""},
  {"rdp.sync-load", Basis::Wiki, "25", "rclk", "n64brew Commands", "bench:rdp-sync-sweep", ""},
  {"rdp.sync-full", Basis::ModelChoice, "50", "rclk", "n64brew Commands: Sync Full waits for every staged pipeline and memory operation, no fixed count; until the memory interface (plan T13) exists the drain is the Sync Pipe stall, as cen64 jgemu charges it (rdp-command-timing.md s.3.5)", "bench:rdp-sync-sweep", "cancels in the Thar0 baseline subtraction; the DP interrupt is raised when it retires"},
  {"rdp.setter", Basis::Wiki, "1", "rclk", "n64brew Pipeline; conflicts with reverted cen64 SETTER 2.68 incl. fetch (jgemu-dpc-probe.md)", "bench:rdp-setter-sweep", "conflict recorded"},
  {"rdp.primitive-base", Basis::Fit, "12", "rclk", "Thar0 RDP-Timing-Tests sample_results.txt alpha all-fail rect: 1-cycle 77,772 = 240 x 324 + 12, 2-cycle 155,052 = 240 x 646 + 12 (hardware-corpora.md); cen64 jgemu rdp_core.c:5346-5362 RECTH 14 includes the 2-word fetch at 1 clk per word (MiSTer RDP_command.vhd), which the DPC front end charges as command fetch", "thar0:alpha-fail-1cycle thar0:alpha-fail-2cycle bench:rdp-rectn", "verify-is-fit: the Thar0 alpha all-fail checks are the fit's data; the only non-circular content is that the 1-cycle and 2-cycle solves agree. Thar0 92/93 (FB + ZB separate) are the same compute-only rectangle, the other 96 configs need memory time (T13), and bench:rdp-rectn (cen64 RECTN, another rectangle size) is reported, not asserted. One rectangle size, so the per-primitive and per-line split is inferred; no triangle setup reference exists, triangles use this value"},
  {"rdp.span-dead-pixels", Basis::Fit, "2", "px", "Thar0 alpha all-fail per-line clocks 324 (1-cycle) and 646 (2-cycle) for 320 px solve to (320 + 2) x clocks-per-pixel + rdp.span-line-gap (hardware-corpora.md); n64brew Pipeline: a dead cycle at the end of every line", "thar0:alpha-fail-1cycle thar0:alpha-fail-2cycle", "verify-is-fit: the Thar0 alpha all-fail checks are the fit's data; the only non-circular content is that the 1-cycle and 2-cycle solves agree. Thar0 92/93 (FB + ZB separate) are the same compute-only rectangle, the other 96 configs need memory time (T13), and bench:rdp-rectn (cen64 RECTN, another rectangle size) is reported, not asserted. Pixel slots the pipeline cycles per span without output; 1- and 2-cycle only. The n64brew Pipeline citation supports the existence of a dead cycle per line (1 slot), not the fitted magnitude of 2"},
  {"rdp.span-line-gap", Basis::Fit, "2", "rclk", "Thar0 alpha all-fail per-line fit (see rdp.span-dead-pixels); MiSTer RDP_raster.vhd LINEIDLE + PREPARELINE = 2 clk per line", "thar0:alpha-fail-1cycle thar0:alpha-fail-2cycle", "verify-is-fit: the Thar0 alpha all-fail checks are the fit's data; the only non-circular content is that the 1-cycle and 2-cycle solves agree. Thar0 92/93 (FB + ZB separate) are the same compute-only rectangle, the other 96 configs need memory time (T13), and bench:rdp-rectn (cen64 RECTN, another rectangle size) is reported, not asserted. Applied to fill and copy spans too, as cen64 applied its span terms (same-silicon assumption)"},
  {"rdp.span-1cycle", Basis::Vendor, "1", "px/rclk", "SDK Table 12-1; cen64 129/128 slope", "thar0:alpha-fail-1cycle", ""},
  {"rdp.span-2cycle", Basis::Vendor, "0.5", "px/rclk", "SDK Table 12-1", "thar0:alpha-fail-2cycle", ""},
  {"rdp.fill-copy-rate", Basis::Vendor, "8", "B/rclk", "SDK 12.1.4/12.1.5", "thar0:fill-mode", ""},
  {"rdp.tmem-load-rate", Basis::Rtl, "8", "B/rclk", "MiSTer RTL and angrylion structure; reverted cen64 law 0.418 B/clk conflicts (jgemu-dpc-probe.md)", "bench:rdp-loadsz-sweep", "conflict recorded; no vendor figure"},
  {"rdp.pipeline-depth", Basis::Derived, "25", "rclk", "cen64 hazard fit D = min(3L-2, 25); n64brew corruption table 0-29 (rdp-command-timing.md s.3.7)", "rdpstat:nosync-1cycle snapper:rect-nosync", "T15"},
  {"rdp.atomic-dead", Basis::Vendor, "35", "rclk", "SDK pro-man 12.2.3: 30 to 40 null cycles (1prim-cost.md)", "bench:rdp-atomic-sweep", "midpoint of a vendor range"},
  {"rdp.span-ram-half", Basis::Measured, "64", "B", "snapper64 216 dumps via the cen64 DPS model (span-ram.md rows 3-5)", "snapper:span-tri", ""},
  {"rdp.span-ram-segment", Basis::Wiki, "16", "B", "DPS_TEST_MODE counters count 16 B segments (span-ram.md)", "snapper:span-tri", ""},
  {"rdp.color-half-pixels-16bpp", Basis::ModelChoice, "32", "px", "span-ram.md question 1: 16 or 32 at 16 bpp, unmeasured", "snapper:span-tri", "calibration #16"},
  {"rdp.read-gate", Basis::Vendor, "IM_RD,Z_CMP", "rule", "SDK 15.7; US 6,166,748 claim 1 (rdp-memory-traffic.md)", "thar0:imrd-1cycle thar0:zcmp", ""},
  {"rdp.write-run", Basis::Measured, "per-contiguous-run", "rule", "snapper64 Span Tri console dumps, 113 shared-octbyte cases (rdp-write-granularity.md)", "snapper:span-tri thar0:alpha-fail-1cycle", "transaction form is inference; content is measured"},
  {"rdp.noise-step", Basis::Measured, "every-rclk", "rule", "Thar0 RDP-Noise dumps re-solved (rdp-noise.md)", "noise:a noise:b noise:c", ""},
  {"rdp.noise-reset", Basis::Measured, "all-ones", "rule", "Thar0 data reproduction (rdp-noise.md)", "noise:a", ""},
  {"rdp.noise-pixel-offset", Basis::ModelChoice, "0", "rclk", "rdp-noise.md item 2: pixel-to-clock offset unknown; 0 until measured", "noise:rect-1016", "calibration #16"},
  {"legacy.clock.vclk-pal", Basis::Legacy, "49656530", "Hz", "ares/n64/system/system.cpp:88", "pending:no-corpus", "no plan unit: PAL is not the target console"},
  {"legacy.cpu.interrupt-entry", Basis::Legacy, "1", "pclk", "ares/n64/cpu/cpu.cpp:102", "nemu64:cop0hazard/softwareinterrupt", "no plan unit: no measurement of the interrupt entry cost was found; T7c built the sampling rule (cpu.irq-sample), not this cost"},
  {"legacy.cpu.nmi-entry", Basis::Legacy, "1", "pclk", "ares/n64/cpu/cpu.cpp:109", "pending:no-corpus", "no plan unit: NMI entry has no timing reference (T7b)"},
  {"legacy.cpu.sysad-frozen-step", Basis::Legacy, "1", "pclk", "ares/n64/cpu/cpu.cpp:114", "pending:no-corpus", "replaced by T6: SysAD port"},
  {"legacy.cpu.icache-fill", Basis::Legacy, "48", "pclk", "ares/n64/cpu/sysad.hpp:60", "bench:ifill-isolated", "replaced by T7d: I-fill through SysAD::fill (cpu.ifill-stall)"},
  {"legacy.cpu.icache-writeback", Basis::Legacy, "48", "pclk", "ares/n64/cpu/sysad.cpp:262", "pending:no-corpus", "replaced by T7d: I-cache CACHE ops through SysAD"},
  {"legacy.pi.cart-read", Basis::Legacy, "250", "pclk", "ares/n64/pi/bus.hpp:63", "pending:no-corpus", "replaced by T8: PI bus timing from the BSD registers"},
  {"legacy.pi.write-busy", Basis::Legacy, "200", "pclk", "ares/n64/pi/bus.hpp:77", "bench:pi-io-write", "replaced by T8: PI I/O busy (pi.io-busy)"},
  {"legacy.si.bus-write", Basis::Legacy, "2150", "rclk", "ares/n64/si/io.cpp:66", "pending:no-corpus", "no plan unit: the SI I/O write busy; T8 left it, no hardware reference"},
  {"legacy.si.dma-read-base", Basis::Legacy, "13600", "rclk", "ares/n64/pif/hle.cpp:203", "bench:si-dma", "no plan unit: SiDma's joybus phase (T8 kept pif.estimateTiming; si.read64-base is the same value); no per-command hardware reference"},
  {"legacy.si.dma-read-controller", Basis::Legacy, "22000", "rclk", "ares/n64/pif/hle.cpp:228", "bench:si-dma", "no plan unit: SiDma's joybus phase (T8 kept pif.estimateTiming); per channel with a device"},
  {"legacy.si.dma-read-empty-port", Basis::Legacy, "18000", "rclk", "ares/n64/pif/hle.cpp:230", "bench:si-dma", "no plan unit: SiDma's joybus phase (T8 kept pif.estimateTiming); per channel without a device"},
  {"legacy.si.dma-read-accessory", Basis::Legacy, "20000", "rclk", "ares/n64/pif/hle.cpp:234", "bench:si-dma", "no plan unit: SiDma's joybus phase (T8 kept pif.estimateTiming); per cartridge channel"},
  {"legacy.si.dma-read-short-command", Basis::Legacy, "1420", "rclk", "ares/n64/pif/hle.cpp:240", "bench:si-dma", "no plan unit: SiDma's joybus phase (T8 kept pif.estimateTiming); per end, skip, reset or padding byte"},
  {"legacy.pif.step-quantum", Basis::Legacy, "40960", "pclk", "ares/n64/pif/hle.cpp:266", "stepcap", "no plan unit: the PIF HLE boot-handshake poll period, a timeline event from T5; the CIC handshake has no timing reference"},
  {"legacy.pif.boot-timeout", Basis::Legacy, "6", "s", "ares/n64/pif/hle.cpp:360", "pending:no-corpus", "no plan unit: CIC boot handshake timeout"},
  {"legacy.ai.power-on-rate", Basis::Legacy, "44100", "Hz", "ares/n64/ai/ai.cpp:92", "pending:no-corpus", "no plan unit: the DAC rate before the first AI_DACRATE write"},
  {"legacy.cart.eeprom-write", Basis::Legacy, "6", "ms", "ares/n64/cartridge/joybus.cpp:48", "pending:no-corpus", "no plan unit: EEPROM write busy time"},
  {"legacy.cart.rtc-tick", Basis::Legacy, "1", "s", "ares/n64/cartridge/rtc.cpp:42", "pending:no-corpus", "no plan unit: cartridge RTC one-second tick"},
  {"legacy.cart.flash-mx-sector-erase", Basis::Legacy, "85", "ms", "ares/n64/cartridge/flash.cpp:4", "pending:no-corpus", "no plan unit: Macronix flash sector erase"},
  {"legacy.cart.flash-mx-chip-erase", Basis::Legacy, "85", "ms", "ares/n64/cartridge/flash.cpp:4", "pending:no-corpus", "no plan unit: Macronix flash chip erase"},
  {"legacy.cart.flash-mx-program", Basis::Legacy, "3500", "us", "ares/n64/cartridge/flash.cpp:4", "pending:no-corpus", "no plan unit: Macronix flash page program"},
  {"legacy.cart.flash-mn63-sector-erase", Basis::Legacy, "280", "ms", "ares/n64/cartridge/flash.cpp:9", "pending:no-corpus", "no plan unit: Matsushita flash sector erase"},
  {"legacy.cart.flash-mn63-chip-erase", Basis::Legacy, "300", "ms", "ares/n64/cartridge/flash.cpp:9", "pending:no-corpus", "no plan unit: Matsushita flash chip erase"},
  {"legacy.cart.flash-mn63-program", Basis::Legacy, "300", "us", "ares/n64/cartridge/flash.cpp:9", "pending:no-corpus", "no plan unit: Matsushita flash page program"},
};

}
