//GENERATED by tools/n64-timing/behaviors.py from ares/n64/timing/behaviors.tsv. Do not edit.
//behaviors.py --check fails when this file, docs/spec/n64-timing.md or tools/n64-timing/checks.tsv
//disagree with the table. Times are Clock values (timing/clock.hpp), in 750 MHz units.

namespace Timing {

enum class Basis : u8 { Measured, Vendor, Datasheet, Wiki, Rtl, Derived, Fit, ModelChoice, Legacy };

struct BehaviorInfo {
  const char* id;
  Basis basis;
  const char* value;
  const char* unit;
  const char* reference;
  const char* verify;
  const char* note;
};

namespace Behavior {
  constexpr s64 ClockUnit = 750000000;  //750000000 Hz
  constexpr Ratio ClockVclk = {5500, 357};  //5500/357 units
  constexpr Clock RiReadHit = {30};  //10 tc
  constexpr Clock RiWriteHit = {12};  //4 tc
  constexpr Clock RiOctbyte = {12};  //4 tc
  constexpr Clock RiRetryClean = {66};  //22 tc
  constexpr Clock RiRetryDirty = {90};  //30 tc
  constexpr Clock RiPostReadGap = {6};  //2 tc
  constexpr Clock RiPostWriteGap = {12};  //4 tc
  constexpr s64 RiMaxBurst = 128;  //128 B
  constexpr Clock RiRefreshClean = {624};  //52 rclk
  constexpr Clock RiRefreshDirty = {648};  //54 rclk
  constexpr bool RiRefreshWaitsForBurst = true;  //1 flag
  constexpr s64 RiRankRefresh = 0;  //0 rank
  constexpr s64 RiRankVi = 1;  //1 rank
  constexpr s64 RiRankOther = 2;  //2 rank
  constexpr Clock RiOverheadRead = {54};  //4.5 rclk
  constexpr Clock RiOverheadWrite = {20};  //1.7 rclk; 20 units, rounded from 20.4
  constexpr Clock RiOverheadRdp = {20};  //20 units
  constexpr Clock RiRequestLatency = {1};  //1 units
  constexpr Clock CpuUncachedReadTotal = {256};  //32 pclk
  constexpr Clock CpuUncachedReadDwordTotal = {296};  //37 pclk
  constexpr Clock CpuDfillTotal = {328};  //41 pclk
  constexpr Clock CpuIfillStall = {360};  //45 pclk
  constexpr Clock CpuDcacheHit = {8};  //1 pclk
  constexpr Clock CpuLdi = {8};  //1 pclk
  constexpr Clock CpuDcb = {8};  //1 pclk
  constexpr Clock CpuMci = {8};  //1 pclk
  constexpr Clock CpuExcRf = {40};  //5 pclk
  constexpr Clock CpuExcEx = {48};  //6 pclk
  constexpr Clock CpuExcFpuUnimpl = {56};  //7 pclk
  constexpr Clock CpuExcFpuArithExtra = {40};  //5 pclk
  constexpr Clock CpuFpuAdd = {24};  //3 pclk
  constexpr Clock CpuFpuMulS = {40};  //5 pclk
  constexpr Clock CpuFpuMulD = {64};  //8 pclk
  constexpr Clock CpuFpuDivS = {232};  //29 pclk
  constexpr Clock CpuFpuDivD = {464};  //58 pclk
  constexpr Clock CpuFpuTrivial = {16};  //2 pclk
  constexpr Clock CpuFpuForward = {8};  //1 pclk
  constexpr Clock CpuLikelyNullified = {8};  //1 pclk
  constexpr Clock CpuMtc0SlowRegs = {16};  //2 pclk
  constexpr Clock CpuCacheIndexOp = {40};  //5 pclk
  constexpr s64 CpuCountWriteLatency = 1;  //1 instr
  constexpr s64 CpuIrqSampleLag = 1;  //1 instr
  constexpr s64 CpuFetchAheadSlots = 3;  //3 instr
  constexpr s64 CpuWbEntries = 4;  //4 entries
  constexpr s64 CpuWbBlockEntries = 2;  //2 entries
  constexpr Clock CpuRcpRegisterRead = {176};  //22 pclk
  constexpr Clock CpuPifRamRead = {23688};  //1974 rclk
  constexpr Clock SysadRdramWritePeriod = {144};  //12 rclk
  constexpr Clock SysadRdramBlockWritePeriod = {144};  //12 rclk
  constexpr Clock SysadRegisterWrite = {60};  //5 rclk
  constexpr s64 SpDmaBurst = 128;  //128 B
  constexpr Ratio SpDmaRateCheck = {13, 2};  //6.5 B/rclk
  constexpr Clock RspSlot = {12};  //1 rclk
  constexpr Clock PiPageSetup = {180};  //15 rclk
  constexpr s64 PiBlockBytes = 128;  //128 B
  constexpr Clock PiBlockWriteback = {336};  //28 rclk
  constexpr Clock PiIoBusy = {1608};  //134 rclk
  constexpr Clock SiWrite64 = {48780};  //4065 rclk
  constexpr Clock SiRead64Base = {163200};  //13600 rclk
  constexpr s64 AiFetchBytes = 8;  //8 B
  constexpr s64 ViLinesPerOutputLine = 3;  //3 lines
  constexpr s64 ViBurst = 128;  //128 B
  constexpr s64 RdpCmdFifoDwords = 30;  //30 dwords
  constexpr s64 RdpCmdFetchBurst = 128;  //128 B
  constexpr s64 RdpXbusFetchRate = 8;  //8 B/rclk
  constexpr Clock RdpSyncPipe = {600};  //50 rclk
  constexpr Clock RdpSyncTile = {396};  //33 rclk
  constexpr Clock RdpSyncLoad = {300};  //25 rclk
  constexpr Clock RdpSyncFull = {600};  //50 rclk
  constexpr Clock RdpSetter = {12};  //1 rclk
  constexpr Clock RdpPrimitiveBase = {144};  //12 rclk
  constexpr s64 RdpSpanDeadPixels = 2;  //2 px
  constexpr Clock RdpSpanLineGap = {24};  //2 rclk
  constexpr s64 RdpSpan1cycle = 1;  //1 px/rclk
  constexpr Ratio RdpSpan2cycle = {1, 2};  //0.5 px/rclk
  constexpr s64 RdpFillCopyRate = 8;  //8 B/rclk
  constexpr s64 RdpTmemLoadRate = 8;  //8 B/rclk
  constexpr Clock RdpPipelineDepth = {300};  //25 rclk
  constexpr Clock RdpAtomicDead = {420};  //35 rclk
  constexpr s64 RdpSpanRamHalf = 64;  //64 B
  constexpr s64 RdpSpanRamSegment = 16;  //16 B
  constexpr s64 RdpColorHalfPixels16bpp = 32;  //32 px
  constexpr Clock RdpNoisePixelOffset = {0};  //0 rclk
}

inline constexpr BehaviorInfo behaviors[] = {
  {"clock.unit", Basis::Derived, "750000000", "Hz", "clocks.md: LCM of RCLK 250, PClock 93.75, RCP 62.5 MHz (X2 x17)", "nemu64:rsp_timing/clock-cpu-vs-rdp", ""},
  {"clock.vclk", Basis::Derived, "5500/357", "units", "clocks.md: VCLK = 315/22 MHz x 17/5 (X1); exact rational", "mm:south-clock-town", "AI and VI share the accumulator; removes the +33 ppm AI truncation"},
  {"scheduler.tie-rank", Basis::ModelChoice, "Bus,Events,SysAD,RDP,RSP,CPU", "order", "none: equal-time ordering between independent RCP blocks is unpublished", "det stepcap unit:timeline", "convention; cannot be observed by a test ROM except through an exact tie"},
  {"ri.read-hit", Basis::Datasheet, "10", "tc", "NEC uPD488170L tReadHit (rdram-bus-arbitration.md B8)", "unit:ri-cost-table nemu64:timing/load-from-uncached-vi-off", ""},
  {"ri.write-hit", Basis::Datasheet, "4", "tc", "NEC uPD488170L tWriteHit (B8)", "unit:ri-cost-table bench:mi-memset-uncached", ""},
  {"ri.octbyte", Basis::Datasheet, "4", "tc", "NEC uPD488170L 2 B per tc (B8)", "unit:ri-cost-table bench:sp-dma-sweep", ""},
  {"ri.retry-clean", Basis::Datasheet, "22", "tc", "NEC tRetrySensedClean = 7+7+8 at IPL3 RasInterval 1/7/10/4 (B8, s.2)", "unit:ri-cost-table nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"ri.retry-dirty", Basis::Datasheet, "30", "tc", "NEC tRetrySensedDirty (B8)", "unit:ri-cost-table bench:dirty-row-sweep", ""},
  {"ri.post-read-gap", Basis::Datasheet, "2", "tc", "NEC tPostMemReadDelay (B8)", "bench:sp-dma-sweep", ""},
  {"ri.post-write-gap", Basis::Datasheet, "4", "tc", "NEC tPostMemWriteDelay (B8)", "bench:sp-dma-sweep", ""},
  {"ri.max-burst", Basis::Wiki, "128", "B", "n64brew RDRAM_Interface Count, 1-16 octbytes (B2)", "unit:ri-split", ""},
  {"ri.bank-of", Basis::Wiki, "addr[22:20]", "map", "n64brew RDRAM_Interface address mapping (B6)", "nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"ri.row-of", Basis::Datasheet, "addr[19:11]", "map", "NEC 2 KiB RowSenseAmpCache (B6)", "nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"ri.refresh-clean", Basis::Vendor, "52", "rclk", "IPL3 6105 RI_REFRESH 0x007E3634 CleanRefreshDelay (B12)", "bench:uncached-vs-hpos", ""},
  {"ri.refresh-dirty", Basis::Vendor, "54", "rclk", "IPL3 6105 RI_REFRESH DirtyRefreshDelay (B12)", "bench:uncached-vs-hpos", ""},
  {"ri.refresh-trigger", Basis::Wiki, "hsync", "event", "n64brew RDRAM_Interface: one SetRR per VI HSYNC (B11)", "bench:uncached-vs-hpos", "SOURCE CONFLICT: rdram-bus-arbitration.md B11 says refresh runs before VI init (H_TOTAL 0x7FF, ~42 us per line); nemu64-test's VI-off loads (nemu64:timing/load-from-uncached-vi-off, nemu64:timing/load-miss-vi-off) average 32.54 pclk uncached, which a 52-rclk holdoff every line would raise by about 2. The model follows the nemu64 data: refresh runs only while the VI is active (vi.cpp VI::line). Reason: it is the only measurement of VI-off timing, and B11's pre-init claim is from n64brew prose, unmeasured. A blank VI sending no HSYNC is consistent with both; a pre-init refresh at the 0x7FF line rate remains unverified"},
  {"ri.refresh-waits-for-burst", Basis::ModelChoice, "1", "flag", "no mid-burst preemption (B5); refresh waits for the in-flight burst", "bench:uncached-vs-hpos", "calibration #16"},
  {"ri.arbitration", Basis::ModelChoice, "rank,arrival,requester,sequence", "order", "none published (B4); VI first is an inference from its hard real-time role", "nemu64:timing/load-miss-vi-on thar0:vi-on-separate-bank", "calibration #16 re-ranks via ri.rank.*; rejected alternatives recorded: fixed list VI,AI,SI,PI,CPU,SP,DP (fable), Refresh>VI>AI>CPU>SI>PI>SP>DPcmd>DPmem (sonnet), MiSTer DDR3Mux order"},
  {"ri.rank.refresh", Basis::Wiki, "0", "rank", "n64brew: refresh holds off every client (B12)", "bench:uncached-vs-hpos", ""},
  {"ri.rank.vi", Basis::ModelChoice, "1", "rank", "inference: VI is the only hard real-time client (B4)", "nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"ri.rank.other", Basis::ModelChoice, "2", "rank", "none published (B4): all other clients first-come first-served", "nemu64:timing/load-miss-vi-on", ""},
  {"ri.overhead-read", Basis::Fit, "4.5", "rclk", "hcs64 SP DMA 3.7 B/pclk = 23 rclk per 128 B minus wire 18.5 (dma-timing.md, B10)", "bench:sp-dma-sweep", "verify-is-fit: bench:sp-dma-sweep reports hcs64's 5.55 B/rclk, the fit's own data, and asserts only the write point; no check decides a read DMA. Direction of hcs64 run unstated"},
  {"ri.overhead-write", Basis::Fit, "1.7", "rclk", "n64brew MI memset RSP DMA 2.58 ms/MiB = 19.7 rclk per 128 B minus wire 18 (B10)", "bench:mi-memset-rspdma", "verify-is-fit: both checks assert n64brew's 2.58 ms/MiB memset (6.5 B/rclk), the data the fit solves, and no other check decides a write DMA"},
  {"ri.overhead-rdp", Basis::ModelChoice, "20", "units", "assumed equal to ri.overhead-write (the 1.7 rclk fit, 20 units after rounding); span-ram.md row 10 says the RDP path is unmeasured", "thar0:imrd-1cycle", "calibration #16"},
  {"ri.request-latency", Basis::ModelChoice, "1", "units", "none published: ADR 0001 Decision 1 needs a request to reach the arbiter after its post, so a decision never races an equal-time post; one unit is the least that does", "det stepcap", ""},
  {"cpu.uncached-read-total", Basis::Measured, "32", "pclk", "nemu64-test cache.rs:288-382 median, VI off", "nemu64:timing/load-from-uncached-vi-off", "sysad.fixed-path is derived from this minus modeled wire"},
  {"cpu.uncached-read-dword-total", Basis::Measured, "37", "pclk", "n64-systembench main.c:572-584 U64 (cited value; ROM is romgen's)", "bench:uncached-sizes", ""},
  {"cpu.dfill-total", Basis::Measured, "41", "pclk", "nemu64-test cache.rs:193-286 median, VI off", "nemu64:timing/load-miss-vi-off", "assumes the nemu64 D-fill measurement is a clean row miss (open row not dirty); a dirty-row miss would add the writeback and the 41 would not be the clean-miss cost"},
  {"cpu.ifill-stall", Basis::Derived, "45", "pclk", "NEC Table 11-2 with M from D-fill (cpu-memory-costs.md)", "bench:ifill-isolated", "no public hardware value; the bench reports"},
  {"cpu.dcache-hit", Basis::Measured, "1", "pclk", "nemu64-test Cached loads and store, 19 cases", "nemu64:timing/cached-loads-and-store", ""},
  {"cpu.ldi", Basis::Vendor, "1", "pclk", "NEC VR4300 UM s.4.6.5; n64brew register-field overlap rule", "nemu64:timing/cpu-register-dependency", ""},
  {"cpu.dcb", Basis::Vendor, "1", "pclk", "NEC VR4300 UM s.4.6.7", "nemu64:timing/cpu-register-dependency", ""},
  {"cpu.mci", Basis::Measured, "1", "pclk", "nemu64-test MFC0 then dependent (C9)", "nemu64:timing/cpu-register-dependency", ""},
  {"cpu.exc-rf", Basis::Measured, "5", "pclk", "nemu64-test Exceptions (BREAK, SYSCALL, RI, CpU)", "nemu64:timing/exceptions", ""},
  {"cpu.exc-ex", Basis::Measured, "6", "pclk", "nemu64-test Exceptions (Ov, Tr, AdEL/AdES)", "nemu64:timing/exceptions", ""},
  {"cpu.exc-fpu-unimpl", Basis::Measured, "7", "pclk", "nemu64-test COP1 JustFire", "nemu64:timing/cop1instructions32", ""},
  {"cpu.exc-fpu-arith-extra", Basis::Measured, "5", "pclk", "nemu64-test: FPU arithmetic exception = op latency + 5 (C1)", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-add", Basis::Measured, "3", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-mul-s", Basis::Measured, "5", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-mul-d", Basis::Measured, "8", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions64", ""},
  {"cpu.fpu-div-s", Basis::Measured, "29", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-div-d", Basis::Measured, "58", "pclk", "nemu64-test COP1 tables", "nemu64:timing/cop1instructions64", ""},
  {"cpu.fpu-trivial", Basis::Measured, "2", "pclk", "nemu64-test COP1 value tables (operand 0, -0, Inf, qNaN)", "nemu64:timing/cop1instructions32", ""},
  {"cpu.fpu-forward", Basis::Measured, "1", "pclk", "nemu64-test COP1RegisterDependency", "nemu64:timing/cop1-register-dependency", ""},
  {"cpu.likely-nullified", Basis::Measured, "1", "pclk", "nemu64-test Likely branch (C8)", "nemu64:timing/likely-branch", ""},
  {"cpu.mtc0-slow-regs", Basis::Measured, "2", "pclk", "nemu64-test Random, EntryLo0/1, EntryHi, reg7 (C5)", "nemu64:timing/individual-instructions", ""},
  {"cpu.cache-index-op", Basis::Measured, "5", "pclk", "nemu64-test CACHE DataIndexLoadTag (C10)", "nemu64:timing/cache", ""},
  {"cpu.count-write-latency", Basis::Measured, "1", "instr", "nemu64-test cop0hazard MTC0/MFC0 COUNT", "nemu64:cop0hazard/count", ""},
  {"cpu.irq-sample-lag", Basis::Measured, "1", "instr", "nemu64-test cop0hazard SoftwareInterrupt", "nemu64:cop0hazard/softwareinterrupt", ""},
  {"cpu.fetch-ahead-slots", Basis::Derived, "3", "instr", "nemu64-test cycle set SMC: a store fewer than 3 slots ahead is not seen", "nemu64:cycle/smc", "fable chose 2; the window is sized so both readings fit, the cycle set decides"},
  {"cpu.dirty-miss-order", Basis::Vendor, "fill-then-writeback", "order", "NEC s.12.5.2-12.5.3 p.304; R4300i datasheet p.8-9 (vr4300-wb.md)", "bench:dirty-miss-isolated", ""},
  {"cpu.wb-entries", Basis::Vendor, "4", "entries", "NEC s.4.9 p.120; R4300i datasheet p.9", "nemu64:timing/uncached-write-buffer", ""},
  {"cpu.wb-block-entries", Basis::Vendor, "2", "entries", "R4300i datasheet p.9", "bench:mi-memset-cached", ""},
  {"cpu.wb-release", Basis::Vendor, "slot", "rule", "NEC 'has a space' (s.4.9) chosen over R4300i datasheet 'emptied'; burst shape only", "bench:wb-fifth-store", "conflict recorded; no public hardware value"},
  {"cpu.rcp-register-read", Basis::Measured, "22", "pclk", "n64-systembench VI_CONTROL read 24 minus about 2 harness (cited value)", "bench:rcp-reg-read", ""},
  {"cpu.pif-ram-read", Basis::Measured, "1974", "rclk", "n64-systembench PIF RAM read (cited value)", "bench:pif-ram-read", ""},
  {"sysad.rdram-write-period", Basis::Fit, "12", "rclk", "n64brew MIPS_Interface memset, 64-bit uncached writes 25.7 ms/MiB = 18.38 pclk = 12.25 rclk per SD (vr4300-wb.md), less refresh (1.3%, rdram-bus-arbitration.md B12), on the SClock grid: 12 rclk gives 18.28 pclk, the rest is inferred, not measured, to be VI fetch contention (plan T11)", "bench:mi-memset-uncached", "verify-is-fit: the uncached memset is the only measurement of an uncached RDRAM write drain and the fit's data. Drain period of one uncached RDRAM write, request to EOK at row hit"},
  {"sysad.rdram-block-write-period", Basis::Fit, "12", "rclk", "n64brew MIPS_Interface memset, 64-bit cached writes 49.8 ms/MiB = 71.24 pclk per line (vr4300-wb.md), less the modeled fill (a dirty row miss behind the victim), the victim write (a clean row miss), the store issues and refresh, on the SClock grid: 12 rclk gives 71.0 pclk, the rest is inferred, not measured, to be VI fetch contention (plan T11)", "bench:mi-memset-cached bench:dirty-miss-isolated", "verify-is-fit: the cached memset is the fit's data and bench:dirty-miss-isolated only reports (no hardware value). Drain period of one D-cache line writeback, request to EOK at row hit; equal to the single-write period"},
  {"sysad.register-write", Basis::ModelChoice, "5", "rclk", "no hardware measurement (vr4300-wb.md, RCP register row); MiSTer memorymux.vhd:346-425 holds a register write 3 RCP clocks after the 2-SClock address and data phases", "pending:no-corpus", "a posted write to an RCP register, the PI or the PIF takes effect this long after it starts draining"},
  {"cpu.random-rule", Basis::Vendor, "decrement-per-pclk", "rule", "NEC UM ch.5; nemu64-test Random (decrement), Random (masking)", "nemu64:timing/random", ""},
  {"sp.dma-burst", Basis::ModelChoice, "128", "B", "inference: RI maximum matches the measured ~20 rclk per 128 B (dma-timing.md)", "bench:sp-dma-sweep", ""},
  {"sp.dma-rate-check", Basis::Measured, "6.5", "B/rclk", "n64brew MI page RSP DMA memset 2.58 ms/MiB; hcs64 5.55 conflicts (direction unstated)", "bench:sp-dma-sweep", "the bench reports both directions"},
  {"rsp.slot", Basis::Wiki, "1", "rclk", "clocks.md: the RSP runs on the RCP clock (n64brew Clock_Timing; SDK pro-man ch.3 RCP 62.5 MHz); one pipeline slot, an issue or a bubble, per clock", "nemu64:rsp_timing/sll", "RSP::Pipeline charges it per issued pair and per stall bubble (ADR 0001 keeps the RSP pipeline as the RSP cost model)"},
  {"pi.page-setup", Basis::Wiki, "15", "rclk", "n64brew PI: 14 + LAT + 1 with LAT separate (dma-timing.md)", "pidma:logs bench:pi-dma-sizes", ""},
  {"pi.block-bytes", Basis::Wiki, "128", "B", "n64brew PI; rasky n64_pi_dma_test", "pidma:logs", ""},
  {"pi.block-writeback", Basis::Derived, "28", "rclk", "dma-timing.md fit to systembench PI DMA rows; the bus model supplies the wire part", "pidma:logs bench:pi-dma-sizes", ""},
  {"pi.io-busy", Basis::Measured, "134", "rclk", "n64-systembench PI I/O W (cited value)", "bench:pi-io-write", ""},
  {"si.write64", Basis::Measured, "4065", "rclk", "n64-systembench SI DMA 64 B to PIF (cited value)", "bench:si-dma", ""},
  {"si.read64-base", Basis::Derived, "13600", "rclk", "ares pif.estimateTiming (systembench-derived)", "bench:si-dma", ""},
  {"ai.fetch-bytes", Basis::Vendor, "8", "B", "US 6,166,748 '8 bytes at a time' (dma-timing.md)", "mm:south-clock-town", "functional; contention effect 0.026% of peak"},
  {"vi.lines-per-output-line", Basis::Vendor, "3", "lines", "SDK pro-man s.24.4; US 6,166,748 FIG. 34 (vi-fetch.md)", "nemu64:timing/load-from-uncached-vi-on-same-bank", ""},
  {"vi.burst", Basis::ModelChoice, "128", "B", "inference from the 64-px X_SCALE erratum and the RI maximum (vi-fetch.md)", "bench:uncached-vs-hpos", ""},
  {"vi.fetch-window", Basis::Wiki, "active-line", "rule", "n64brew VI_H_VIDEO; US 6,166,748 'in synchronism with the line scanning'", "bench:uncached-vs-hpos", ""},
  {"rdp.cmd-fifo-dwords", Basis::Wiki, "30", "dwords", "n64-systemtest rdp/mod.rs:21-23 author note: CURRENT reaches START+240 while frozen", "rdpstat:current-prefetch", "no test asserts it; MiSTer uses 64; calibration #16"},
  {"rdp.cmd-fetch-burst", Basis::ModelChoice, "128", "B", "RI maximum; MiSTer fetches <= 22 words", "rdpstat:current-prefetch", "calibration #16"},
  {"rdp.xbus-fetch-rate", Basis::ModelChoice, "8", "B/rclk", "cen64 jgemu interface.c fetches commands 64 bits per clock (rdp-command-timing.md, Command fetch row); the X bus is private to the RSP and RDP, so no RI traffic", "rdpstat:xbus", "no hardware measurement"},
  {"rdp.sync-pipe", Basis::Wiki, "50", "rclk", "n64brew Commands (Tharo rev 5366)", "bench:rdp-sync-sweep", ""},
  {"rdp.sync-tile", Basis::Wiki, "33", "rclk", "n64brew Commands", "bench:rdp-sync-sweep", ""},
  {"rdp.sync-load", Basis::Wiki, "25", "rclk", "n64brew Commands", "bench:rdp-sync-sweep", ""},
  {"rdp.sync-full", Basis::ModelChoice, "50", "rclk", "n64brew Commands: Sync Full waits for every staged pipeline and memory operation, no fixed count; until the memory interface (plan T13) exists the drain is the Sync Pipe stall, as cen64 jgemu charges it (rdp-command-timing.md s.3.5)", "bench:rdp-sync-sweep", "cancels in the Thar0 baseline subtraction; the DP interrupt is raised when it retires"},
  {"rdp.setter", Basis::Wiki, "1", "rclk", "n64brew Pipeline; conflicts with reverted cen64 SETTER 2.68 incl. fetch (jgemu-dpc-probe.md)", "bench:rdp-setter-sweep", "conflict recorded"},
  {"rdp.primitive-base", Basis::Fit, "12", "rclk", "Thar0 RDP-Timing-Tests sample_results.txt alpha all-fail rect: 1-cycle 77,772 = 240 x 324 + 12, 2-cycle 155,052 = 240 x 646 + 12 (hardware-corpora.md); cen64 jgemu rdp_core.c:5346-5362 RECTH 14 includes the 2-word fetch at 1 clk per word (MiSTer RDP_command.vhd), which the DPC front end charges as command fetch", "thar0:alpha-fail-1cycle thar0:alpha-fail-2cycle bench:rdp-rectn", "verify-is-fit: the Thar0 alpha all-fail checks are the fit's data; the only non-circular content is that the 1-cycle and 2-cycle solves agree. Thar0 92/93 (FB + ZB separate) are the same compute-only rectangle, the other 96 configs need memory time (T13), and bench:rdp-rectn (cen64 RECTN, another rectangle size) is reported, not asserted. One rectangle size, so the per-primitive and per-line split is inferred; no triangle setup reference exists, triangles use this value"},
  {"rdp.span-dead-pixels", Basis::Fit, "2", "px", "Thar0 alpha all-fail per-line clocks 324 (1-cycle) and 646 (2-cycle) for 320 px solve to (320 + 2) x clocks-per-pixel + rdp.span-line-gap (hardware-corpora.md); n64brew Pipeline: a dead cycle at the end of every line", "thar0:alpha-fail-1cycle thar0:alpha-fail-2cycle", "verify-is-fit: the Thar0 alpha all-fail checks are the fit's data; the only non-circular content is that the 1-cycle and 2-cycle solves agree. Thar0 92/93 (FB + ZB separate) are the same compute-only rectangle, the other 96 configs need memory time (T13), and bench:rdp-rectn (cen64 RECTN, another rectangle size) is reported, not asserted. Pixel slots the pipeline cycles per span without output; 1- and 2-cycle only. The n64brew Pipeline citation supports the existence of a dead cycle per line (1 slot), not the fitted magnitude of 2"},
  {"rdp.span-line-gap", Basis::Fit, "2", "rclk", "Thar0 alpha all-fail per-line fit (see rdp.span-dead-pixels); MiSTer RDP_raster.vhd LINEIDLE + PREPARELINE = 2 clk per line", "thar0:alpha-fail-1cycle thar0:alpha-fail-2cycle", "verify-is-fit: the Thar0 alpha all-fail checks are the fit's data; the only non-circular content is that the 1-cycle and 2-cycle solves agree. Thar0 92/93 (FB + ZB separate) are the same compute-only rectangle, the other 96 configs need memory time (T13), and bench:rdp-rectn (cen64 RECTN, another rectangle size) is reported, not asserted. Applied to fill and copy spans too, as cen64 applied its span terms (same-silicon assumption)"},
  {"rdp.span-1cycle", Basis::Vendor, "1", "px/rclk", "SDK Table 12-1; cen64 129/128 slope", "thar0:alpha-fail-1cycle", ""},
  {"rdp.span-2cycle", Basis::Vendor, "0.5", "px/rclk", "SDK Table 12-1", "thar0:alpha-fail-2cycle", ""},
  {"rdp.fill-copy-rate", Basis::Vendor, "8", "B/rclk", "SDK 12.1.4/12.1.5", "thar0:fill-mode", ""},
  {"rdp.tmem-load-rate", Basis::Rtl, "8", "B/rclk", "MiSTer RTL and angrylion structure; reverted cen64 law 0.418 B/clk conflicts (jgemu-dpc-probe.md)", "bench:rdp-loadsz-sweep", "conflict recorded; no vendor figure"},
  {"rdp.pipeline-depth", Basis::Derived, "25", "rclk", "cen64 hazard fit D = min(3L-2, 25); n64brew corruption table 0-29 (rdp-command-timing.md s.3.7)", "rdpstat:nosync-1cycle snapper:rect-nosync", "T15"},
  {"rdp.atomic-dead", Basis::Vendor, "35", "rclk", "SDK pro-man 12.2.3: 30 to 40 null cycles (1prim-cost.md)", "bench:rdp-atomic-sweep", "midpoint of a vendor range"},
  {"rdp.span-ram-half", Basis::Measured, "64", "B", "snapper64 216 dumps via the cen64 DPS model (span-ram.md rows 3-5)", "snapper:span-tri", ""},
  {"rdp.span-ram-segment", Basis::Wiki, "16", "B", "DPS_TEST_MODE counters count 16 B segments (span-ram.md)", "snapper:span-tri", ""},
  {"rdp.color-half-pixels-16bpp", Basis::ModelChoice, "32", "px", "span-ram.md question 1: 16 or 32 at 16 bpp, unmeasured", "snapper:span-tri", "calibration #16"},
  {"rdp.read-gate", Basis::Vendor, "IM_RD,Z_CMP", "rule", "SDK 15.7; US 6,166,748 claim 1 (rdp-memory-traffic.md)", "thar0:imrd-1cycle thar0:zcmp", ""},
  {"rdp.write-run", Basis::Measured, "per-contiguous-run", "rule", "snapper64 Span Tri console dumps, 113 shared-octbyte cases (rdp-write-granularity.md)", "snapper:span-tri thar0:alpha-fail-1cycle", "transaction form is inference; content is measured"},
  {"rdp.noise-step", Basis::Measured, "every-rclk", "rule", "Thar0 RDP-Noise dumps re-solved (rdp-noise.md)", "noise:a noise:b noise:c", ""},
  {"rdp.noise-reset", Basis::Measured, "all-ones", "rule", "Thar0 data reproduction (rdp-noise.md)", "noise:a", ""},
  {"rdp.noise-pixel-offset", Basis::ModelChoice, "0", "rclk", "rdp-noise.md item 2: pixel-to-clock offset unknown; 0 until measured", "noise:rect-1016", "calibration #16"},
  {"legacy.clock.vclk-pal", Basis::Legacy, "49656530", "Hz", "ares/n64/system/system.cpp:88", "pending:no-corpus", "no plan unit: PAL is not the target console"},
  {"legacy.cpu.instruction", Basis::Legacy, "1", "pclk", "ares/n64/cpu/memory.cpp:148", "nemu64:timing/just-nops", "replaced by T7a: Pipeline::issue"},
  {"legacy.cpu.interrupt-entry", Basis::Legacy, "1", "pclk", "ares/n64/cpu/cpu.cpp:96", "nemu64:cop0hazard/softwareinterrupt", "replaced by T7c: interrupt sampling lag (cpu.irq-sample-lag)"},
  {"legacy.cpu.nmi-entry", Basis::Legacy, "1", "pclk", "ares/n64/cpu/cpu.cpp:104", "pending:no-corpus", "replaced by T7b: exception stage costs"},
  {"legacy.cpu.sysad-frozen-step", Basis::Legacy, "1", "pclk", "ares/n64/cpu/cpu.cpp:109", "pending:no-corpus", "replaced by T6: SysAD port"},
  {"legacy.cpu.address-error", Basis::Legacy, "1", "pclk", "ares/n64/cpu/memory.cpp:202", "nemu64:timing/exceptions", "replaced by T7b: exception stage costs (cpu.exc-ex)"},
  {"legacy.cpu.icache-fill", Basis::Legacy, "48", "pclk", "ares/n64/cpu/sysad.hpp:60", "bench:ifill-isolated", "replaced by T7d: I-fill through SysAD::fill (cpu.ifill-stall)"},
  {"legacy.cpu.icache-writeback", Basis::Legacy, "48", "pclk", "ares/n64/cpu/sysad.cpp:262", "pending:no-corpus", "replaced by T7d: I-cache CACHE ops through SysAD"},
  {"legacy.cpu.mult", Basis::Legacy, "5", "pclk", "ares/n64/cpu/interpreter-ipu.cpp:640", "nemu64:timing/mult-div-interlock", "replaced by T7a: OpTiming"},
  {"legacy.cpu.dmult", Basis::Legacy, "8", "pclk", "ares/n64/cpu/interpreter-ipu.cpp:349", "nemu64:timing/mult-div-interlock", "replaced by T7a: OpTiming"},
  {"legacy.cpu.div", Basis::Legacy, "37", "pclk", "ares/n64/cpu/interpreter-ipu.cpp:315", "nemu64:timing/mult-div-interlock", "replaced by T7a: OpTiming"},
  {"legacy.cpu.ddiv", Basis::Legacy, "69", "pclk", "ares/n64/cpu/interpreter-ipu.cpp:289", "nemu64:timing/mult-div-interlock", "replaced by T7a: OpTiming"},
  {"legacy.cpu.fpu-add", Basis::Legacy, "3", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:470", "nemu64:timing/cop1instructions32 nemu64:timing/cop1instructions64", "replaced by T7a: OpTiming (cpu.fpu-add)"},
  {"legacy.cpu.fpu-mul-s", Basis::Legacy, "5", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:875", "nemu64:timing/cop1instructions32", "replaced by T7a: OpTiming (cpu.fpu-mul-s)"},
  {"legacy.cpu.fpu-mul-d", Basis::Legacy, "8", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:885", "nemu64:timing/cop1instructions64", "replaced by T7a: OpTiming (cpu.fpu-mul-d)"},
  {"legacy.cpu.fpu-div-s", Basis::Legacy, "29", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:810", "nemu64:timing/cop1instructions32", "replaced by T7a: OpTiming (cpu.fpu-div-s)"},
  {"legacy.cpu.fpu-div-d", Basis::Legacy, "58", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:820", "nemu64:timing/cop1instructions64", "replaced by T7a: OpTiming (cpu.fpu-div-d)"},
  {"legacy.cpu.fpu-sqrt-s", Basis::Legacy, "29", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:953", "nemu64:timing/cop1instructions32", "replaced by T7a: OpTiming"},
  {"legacy.cpu.fpu-sqrt-d", Basis::Legacy, "58", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:963", "nemu64:timing/cop1instructions64", "replaced by T7a: OpTiming"},
  {"legacy.cpu.fpu-convert", Basis::Legacy, "5", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:489", "nemu64:timing/cop1instructions32 nemu64:timing/cop1instructions64", "replaced by T7a: OpTiming; CVT, ROUND, TRUNC, CEIL and FLOOR except CVT.S.D"},
  {"legacy.cpu.fpu-cvt-s-d", Basis::Legacy, "2", "pclk", "ares/n64/cpu/interpreter-fpu.cpp:706", "nemu64:timing/cop1instructions64", "replaced by T7a: OpTiming"},
  {"legacy.pi.cart-read", Basis::Legacy, "250", "pclk", "ares/n64/pi/bus.hpp:63", "pending:no-corpus", "replaced by T8: PI bus timing from the BSD registers"},
  {"legacy.pi.write-busy", Basis::Legacy, "200", "pclk", "ares/n64/pi/bus.hpp:77", "bench:pi-io-write", "replaced by T8: PI I/O busy (pi.io-busy)"},
  {"legacy.pi.dma-page-setup", Basis::Legacy, "14", "rclk", "ares/n64/pi/dma.cpp:103", "pidma:logs bench:pi-dma-sizes", "replaced by T8: PiDma per page, 14 + BSD LAT + 1 (pi.page-setup)"},
  {"legacy.pi.dma-bytes-per-pulse", Basis::Legacy, "2", "B", "ares/n64/pi/dma.cpp:104", "pidma:logs", "replaced by T8: PiDma; one PWD + RLS pulse per halfword"},
  {"legacy.pi.dma-buffer-writeback", Basis::Legacy, "28", "rclk", "ares/n64/pi/dma.cpp:105", "pidma:logs bench:pi-dma-sizes", "replaced by T8: PiDma block writeback through the RI (pi.block-writeback)"},
  {"legacy.pi.dma-partial-byte", Basis::Legacy, "1", "rclk", "ares/n64/pi/dma.cpp:106", "pidma:logs", "replaced by T8: PiDma partial block"},
  {"legacy.si.bus-write", Basis::Legacy, "2150", "rclk", "ares/n64/si/io.cpp:66", "pending:no-corpus", "replaced by T8: SiDma"},
  {"legacy.si.dma-write64", Basis::Legacy, "4065", "rclk", "ares/n64/si/io.cpp:103", "bench:si-dma", "replaced by T8: SiDma (si.write64)"},
  {"legacy.si.dma-read-base", Basis::Legacy, "13600", "rclk", "ares/n64/pif/hle.cpp:203", "bench:si-dma", "replaced by T8: SiDma (si.read64-base)"},
  {"legacy.si.dma-read-controller", Basis::Legacy, "22000", "rclk", "ares/n64/pif/hle.cpp:228", "bench:si-dma", "replaced by T8: SiDma; per channel with a device"},
  {"legacy.si.dma-read-empty-port", Basis::Legacy, "18000", "rclk", "ares/n64/pif/hle.cpp:230", "bench:si-dma", "replaced by T8: SiDma; per channel without a device"},
  {"legacy.si.dma-read-accessory", Basis::Legacy, "20000", "rclk", "ares/n64/pif/hle.cpp:234", "bench:si-dma", "replaced by T8: SiDma; per cartridge channel"},
  {"legacy.si.dma-read-short-command", Basis::Legacy, "1420", "rclk", "ares/n64/pif/hle.cpp:240", "bench:si-dma", "replaced by T8: SiDma; per end, skip, reset or padding byte"},
  {"legacy.pif.step-quantum", Basis::Legacy, "40960", "pclk", "ares/n64/pif/hle.cpp:266", "stepcap", "no plan unit: the PIF HLE boot-handshake poll period, a timeline event from T5; the CIC handshake has no timing reference"},
  {"legacy.pif.boot-timeout", Basis::Legacy, "6", "s", "ares/n64/pif/hle.cpp:360", "pending:no-corpus", "no plan unit: CIC boot handshake timeout"},
  {"legacy.rsp.dma-bytes-per-rclk", Basis::Legacy, "8", "B", "ares/n64/rsp/dma.cpp:12", "bench:sp-dma-sweep", "replaced by T8: SpDma 128 B bursts through the RI (sp.dma-burst)"},
  {"legacy.ai.power-on-rate", Basis::Legacy, "44100", "Hz", "ares/n64/ai/ai.cpp:75", "pending:no-corpus", "no plan unit: the DAC rate before the first AI_DACRATE write"},
  {"legacy.cart.eeprom-write", Basis::Legacy, "6", "ms", "ares/n64/cartridge/joybus.cpp:48", "pending:no-corpus", "no plan unit: EEPROM write busy time"},
  {"legacy.cart.rtc-tick", Basis::Legacy, "1", "s", "ares/n64/cartridge/rtc.cpp:42", "pending:no-corpus", "no plan unit: cartridge RTC one-second tick"},
  {"legacy.cart.flash-mx-sector-erase", Basis::Legacy, "85", "ms", "ares/n64/cartridge/flash.cpp:4", "pending:no-corpus", "no plan unit: Macronix flash sector erase"},
  {"legacy.cart.flash-mx-chip-erase", Basis::Legacy, "85", "ms", "ares/n64/cartridge/flash.cpp:4", "pending:no-corpus", "no plan unit: Macronix flash chip erase"},
  {"legacy.cart.flash-mx-program", Basis::Legacy, "3500", "us", "ares/n64/cartridge/flash.cpp:4", "pending:no-corpus", "no plan unit: Macronix flash page program"},
  {"legacy.cart.flash-mn63-sector-erase", Basis::Legacy, "280", "ms", "ares/n64/cartridge/flash.cpp:9", "pending:no-corpus", "no plan unit: Matsushita flash sector erase"},
  {"legacy.cart.flash-mn63-chip-erase", Basis::Legacy, "300", "ms", "ares/n64/cartridge/flash.cpp:9", "pending:no-corpus", "no plan unit: Matsushita flash chip erase"},
  {"legacy.cart.flash-mn63-program", Basis::Legacy, "300", "us", "ares/n64/cartridge/flash.cpp:9", "pending:no-corpus", "no plan unit: Matsushita flash page program"},
};

}
